# Generated by Django 5.2.4 on 2025-08-04 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0007_group_slug_delete_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do Backup"),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("database", "Banco de Dados"),
                            ("media", "Arquivos de Mídia"),
                            ("configuration", "Configurações"),
                            ("full", "Backup Completo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Criado"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                            ("corrupted", "Corrompido"),
                            ("deleted", "Deletado"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="Caminho do Arquivo"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="Tamanho do Arquivo (bytes)"),
                ),
                (
                    "sha256_hash",
                    models.CharField(max_length=64, verbose_name="Hash SHA256"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "metadata",
                    models.JSONField(default=dict, verbose_name="Metadados Adicionais"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadados de Backup",
                "verbose_name_plural": "Metadados de Backups",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["backup_type", "-created_at"],
                        name="config_back_backup__878e48_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="config_back_status_b26f66_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="config_back_created_376172_idx",
                    ),
                ],
            },
        ),
    ]
