# Generated by Django 5.2.4 on 2025-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0009_backuppolicy_backupjob_backuprole_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupmetadata",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Criado"),
                    ("in_progress", "Em Progresso"),
                    ("completed", "Concluído"),
                    ("failed", "Falhou"),
                    ("corrupted", "Corrompido"),
                    ("deleted", "Deletado"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
