# Generated by Django 5.2.4 on 2025-07-31 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='Autor/Criador')),
                ('narrator', models.CharField(blank=True, max_length=120, verbose_name='Narrador/Apresentador')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('video_file', models.FileField(blank=True, help_text='Formatos suportados: MP4, WebM, OGG', null=True, upload_to='videobooks/videos/', verbose_name='Arquivo de Vídeo')),
                ('thumbnail', models.ImageField(blank=True, help_text='Imagem de capa do vídeo', null=True, upload_to='videobooks/thumbnails/', verbose_name='Thumbnail')),
                ('external_url', models.URLField(blank=True, help_text='Link para vídeo externo (YouTube, Vimeo, etc.)', verbose_name='URL Externa')),
                ('category', models.CharField(choices=[('podcast', 'Podcast'), ('audiobook', 'Áudio Livro'), ('lecture', 'Aula/Palestra'), ('documentary', 'Documentário'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Categoria')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_public', models.BooleanField(default=True, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conteúdo em Vídeo',
                'verbose_name_plural': 'Conteúdos em Vídeo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='audiobooks__title_30d154_idx'), models.Index(fields=['category'], name='audiobooks__categor_a02908_idx'), models.Index(fields=['created_at'], name='audiobooks__created_0fa253_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='audiobooks.videoaudio')),
            ],
            options={
                'verbose_name': 'Vídeo Favorito',
                'verbose_name_plural': 'Vídeos Favoritos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audiobooks__user_id_de41ee_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.FloatField(default=0.0, verbose_name='Tempo Atual (segundos)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('last_played', models.DateTimeField(auto_now=True, verbose_name='Última reprodução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.videoaudio')),
            ],
            options={
                'verbose_name': 'Progresso de Vídeo',
                'verbose_name_plural': 'Progressos de Vídeos',
                'indexes': [models.Index(fields=['user', 'video'], name='audiobooks__user_id_bd96c1_idx'), models.Index(fields=['last_played'], name='audiobooks__last_pl_7c0374_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
