# Generated by Django 5.2.4 on 2025-08-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0002_category_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videoaudio',
            new_name='audiobooks__categor_01d2fd_idx',
            old_name='audiobooks__categor_a02908_idx',
        ),
        migrations.AddField(
            model_name='videoaudio',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AddIndex(
            model_name='videoaudio',
            index=models.Index(fields=['views'], name='audiobooks__views_b75ba7_idx'),
        ),
    ]
