# Generated by Django 5.2.4 on 2025-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0003_volume_remove_capitulo_chapter_slug_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
