# Generated by Django 5.2.4 on 2025-07-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0005_manga_criado_por_manga_manga_criado_por_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='extracted',
            field=models.BooleanField(default=False, help_text='Indica se as páginas do volume foram extraídas com sucesso', verbose_name='Extraído?'),
        ),
    ]
