# Generated by Django 5.2.4 on 2025-08-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_volume_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de visualizações do mangá', verbose_name='Visualizações'),
        ),
    ]
