# Generated by Django 5.2.4 on 2025-08-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_manga_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug para URL amigável', max_length=255, verbose_name='Slug'),
        ),
    ]
