# Generated by Django 5.2.4 on 2025-08-07 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0008_pagina_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado em"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "session_duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duração da Sessão (segundos)"
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_history",
                        to="mangas.capitulo",
                        verbose_name="Capítulo",
                    ),
                ),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_history",
                        to="mangas.manga",
                        verbose_name="Mangá",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Leitura",
                "verbose_name_plural": "Históricos de Leitura",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "started_at"],
                        name="reading_history_user_date_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_page",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Página atual onde o usuário parou",
                        verbose_name="Página Atual",
                    ),
                ),
                (
                    "total_pages",
                    models.PositiveIntegerField(
                        help_text="Total de páginas do capítulo",
                        verbose_name="Total de Páginas",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Se o capítulo foi completamente lido",
                        verbose_name="Concluído",
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última leitura",
                        verbose_name="Última Leitura",
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tempo total gasto lendo este capítulo",
                        verbose_name="Tempo de Leitura (segundos)",
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to="mangas.capitulo",
                        verbose_name="Capítulo",
                    ),
                ),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to="mangas.manga",
                        verbose_name="Mangá",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Leitura",
                "verbose_name_plural": "Progressos de Leitura",
                "ordering": ["-last_read_at"],
                "indexes": [
                    models.Index(fields=["user", "manga"], name="rp_user_manga_idx"),
                    models.Index(
                        fields=["user", "last_read_at"], name="rp_user_date_idx"
                    ),
                    models.Index(
                        fields=["manga", "capitulo"], name="rp_manga_chapter_idx"
                    ),
                ],
                "unique_together": {("user", "manga", "capitulo")},
            },
        ),
    ]
