# Generated by Django 5.2.4 on 2025-08-05 12:56

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_is_featured_book_is_public_book_views_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_readers", models.IntegerField(default=0)),
                (
                    "average_reading_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("completion_rate", models.FloatField(default=0.0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("total_reading_sessions", models.IntegerField(default=0)),
                ("most_read_pages", models.JSONField(default=list)),
                ("reading_patterns", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Analytics",
                "verbose_name_plural": "Book Analytics",
            },
        ),
        migrations.CreateModel(
            name="ReadingGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("daily_pages", "Páginas por Dia"),
                            ("daily_time", "Tempo por Dia"),
                            ("weekly_books", "Livros por Semana"),
                            ("monthly_books", "Livros por Mês"),
                            ("yearly_books", "Livros por Ano"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_value", models.IntegerField()),
                ("current_progress", models.IntegerField(default=0)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativa"),
                            ("completed", "Concluída"),
                            ("paused", "Pausada"),
                            ("failed", "Falhada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("pages_read", models.IntegerField(default=0)),
                ("reading_speed", models.FloatField(blank=True, null=True)),
                ("current_page", models.IntegerField(default=1)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                        ],
                        default="desktop",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ReadingStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_reading_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("total_pages_read", models.IntegerField(default=0)),
                ("total_books_completed", models.IntegerField(default=0)),
                ("average_reading_speed", models.FloatField(default=0.0)),
                ("favorite_reading_time", models.TimeField(blank=True, null=True)),
                (
                    "longest_session",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("best_streak", models.IntegerField(default=0)),
                ("last_reading_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading Statistics",
                "verbose_name_plural": "Reading Statistics",
            },
        ),
    ]
