# Generated by Django 5.2.4 on 2025-08-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookanalytics_readinggoal_readingsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinggoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='readingsession',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readingsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='readingstatistics',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookAnalytics',
        ),
        migrations.DeleteModel(
            name='ReadingGoal',
        ),
        migrations.DeleteModel(
            name='ReadingSession',
        ),
        migrations.DeleteModel(
            name='ReadingStatistics',
        ),
    ]
