# Generated by Django 5.2.4 on 2025-08-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_category_name_alter_tag_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
