# Generated by Django 5.2.4 on 2025-08-04 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_remove_comment_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Nome da categoria",
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="nome",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Nome da tag",
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="nome",
            ),
        ),
    ]
